//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntrinsicsDude {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color SyntaxHighlighting_Opcode {
            get {
                return ((global::System.Drawing.Color)(this["SyntaxHighlighting_Opcode"]));
            }
            set {
                this["SyntaxHighlighting_Opcode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkRed")]
        public global::System.Drawing.Color SyntaxHighlighting_Register {
            get {
                return ((global::System.Drawing.Color)(this["SyntaxHighlighting_Register"]));
            }
            set {
                this["SyntaxHighlighting_Register"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkOrange")]
        public global::System.Drawing.Color SyntaxHighlighting_Misc {
            get {
                return ((global::System.Drawing.Color)(this["SyntaxHighlighting_Misc"]));
            }
            set {
                this["SyntaxHighlighting_Misc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SyntaxHighlighting_On {
            get {
                return ((bool)(this["SyntaxHighlighting_On"]));
            }
            set {
                this["SyntaxHighlighting_On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CodeCompletion_On {
            get {
                return ((bool)(this["CodeCompletion_On"]));
            }
            set {
                this["CodeCompletion_On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hjlebbink.github.io/x86doc/html/")]
        public string AsmDoc_url {
            get {
                return ((string)(this["AsmDoc_url"]));
            }
            set {
                this["AsmDoc_url"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AsmDoc_On {
            get {
                return ((bool)(this["AsmDoc_On"]));
            }
            set {
                this["AsmDoc_On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_MMX {
            get {
                return ((bool)(this["ARCH_MMX"]));
            }
            set {
                this["ARCH_MMX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_SSE {
            get {
                return ((bool)(this["ARCH_SSE"]));
            }
            set {
                this["ARCH_SSE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_SSE2 {
            get {
                return ((bool)(this["ARCH_SSE2"]));
            }
            set {
                this["ARCH_SSE2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_SSE3 {
            get {
                return ((bool)(this["ARCH_SSE3"]));
            }
            set {
                this["ARCH_SSE3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_SSSE3 {
            get {
                return ((bool)(this["ARCH_SSSE3"]));
            }
            set {
                this["ARCH_SSSE3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_SSE41 {
            get {
                return ((bool)(this["ARCH_SSE41"]));
            }
            set {
                this["ARCH_SSE41"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_SSE42 {
            get {
                return ((bool)(this["ARCH_SSE42"]));
            }
            set {
                this["ARCH_SSE42"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_AVX {
            get {
                return ((bool)(this["ARCH_AVX"]));
            }
            set {
                this["ARCH_AVX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_AVX2 {
            get {
                return ((bool)(this["ARCH_AVX2"]));
            }
            set {
                this["ARCH_AVX2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_AVX512VL {
            get {
                return ((bool)(this["ARCH_AVX512VL"]));
            }
            set {
                this["ARCH_AVX512VL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_AVX512DQ {
            get {
                return ((bool)(this["ARCH_AVX512DQ"]));
            }
            set {
                this["ARCH_AVX512DQ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_AVX512BW {
            get {
                return ((bool)(this["ARCH_AVX512BW"]));
            }
            set {
                this["ARCH_AVX512BW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_AVX512ER {
            get {
                return ((bool)(this["ARCH_AVX512ER"]));
            }
            set {
                this["ARCH_AVX512ER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_AVX512F {
            get {
                return ((bool)(this["ARCH_AVX512F"]));
            }
            set {
                this["ARCH_AVX512F"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_AVX512CD {
            get {
                return ((bool)(this["ARCH_AVX512CD"]));
            }
            set {
                this["ARCH_AVX512CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_BMI1 {
            get {
                return ((bool)(this["ARCH_BMI1"]));
            }
            set {
                this["ARCH_BMI1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_BMI2 {
            get {
                return ((bool)(this["ARCH_BMI2"]));
            }
            set {
                this["ARCH_BMI2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_FMA {
            get {
                return ((bool)(this["ARCH_FMA"]));
            }
            set {
                this["ARCH_FMA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_MPX {
            get {
                return ((bool)(this["ARCH_MPX"]));
            }
            set {
                this["ARCH_MPX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SignatureHelp_On {
            get {
                return ((bool)(this["SignatureHelp_On"]));
            }
            set {
                this["SignatureHelp_On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_ADX {
            get {
                return ((bool)(this["ARCH_ADX"]));
            }
            set {
                this["ARCH_ADX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_FP16C {
            get {
                return ((bool)(this["ARCH_FP16C"]));
            }
            set {
                this["ARCH_FP16C"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_PCLMULQDQ {
            get {
                return ((bool)(this["ARCH_PCLMULQDQ"]));
            }
            set {
                this["ARCH_PCLMULQDQ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_CLFLUSHOPT {
            get {
                return ((bool)(this["ARCH_CLFLUSHOPT"]));
            }
            set {
                this["ARCH_CLFLUSHOPT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_FXSR {
            get {
                return ((bool)(this["ARCH_FXSR"]));
            }
            set {
                this["ARCH_FXSR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_KNCNI {
            get {
                return ((bool)(this["ARCH_KNCNI"]));
            }
            set {
                this["ARCH_KNCNI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_AES {
            get {
                return ((bool)(this["ARCH_AES"]));
            }
            set {
                this["ARCH_AES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool USE_SVML {
            get {
                return ((bool)(this["USE_SVML"]));
            }
            set {
                this["USE_SVML"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_AVX512PF {
            get {
                return ((bool)(this["ARCH_AVX512PF"]));
            }
            set {
                this["ARCH_AVX512PF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_AVX512IFMA52 {
            get {
                return ((bool)(this["ARCH_AVX512IFMA52"]));
            }
            set {
                this["ARCH_AVX512IFMA52"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_AVX512VBMI {
            get {
                return ((bool)(this["ARCH_AVX512VBMI"]));
            }
            set {
                this["ARCH_AVX512VBMI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_LZCNT {
            get {
                return ((bool)(this["ARCH_LZCNT"]));
            }
            set {
                this["ARCH_LZCNT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_INVPCID {
            get {
                return ((bool)(this["ARCH_INVPCID"]));
            }
            set {
                this["ARCH_INVPCID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_MONITOR {
            get {
                return ((bool)(this["ARCH_MONITOR"]));
            }
            set {
                this["ARCH_MONITOR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_POPCNT {
            get {
                return ((bool)(this["ARCH_POPCNT"]));
            }
            set {
                this["ARCH_POPCNT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_RDRAND {
            get {
                return ((bool)(this["ARCH_RDRAND"]));
            }
            set {
                this["ARCH_RDRAND"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_RDSEED {
            get {
                return ((bool)(this["ARCH_RDSEED"]));
            }
            set {
                this["ARCH_RDSEED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_TSC {
            get {
                return ((bool)(this["ARCH_TSC"]));
            }
            set {
                this["ARCH_TSC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_RDTSCP {
            get {
                return ((bool)(this["ARCH_RDTSCP"]));
            }
            set {
                this["ARCH_RDTSCP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_FSGSBASE {
            get {
                return ((bool)(this["ARCH_FSGSBASE"]));
            }
            set {
                this["ARCH_FSGSBASE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_SHA {
            get {
                return ((bool)(this["ARCH_SHA"]));
            }
            set {
                this["ARCH_SHA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_RTM {
            get {
                return ((bool)(this["ARCH_RTM"]));
            }
            set {
                this["ARCH_RTM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_XSAVE {
            get {
                return ((bool)(this["ARCH_XSAVE"]));
            }
            set {
                this["ARCH_XSAVE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_XSAVEC {
            get {
                return ((bool)(this["ARCH_XSAVEC"]));
            }
            set {
                this["ARCH_XSAVEC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_XSS {
            get {
                return ((bool)(this["ARCH_XSS"]));
            }
            set {
                this["ARCH_XSS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_XSAVEOPT {
            get {
                return ((bool)(this["ARCH_XSAVEOPT"]));
            }
            set {
                this["ARCH_XSAVEOPT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_PREFETCHWT1 {
            get {
                return ((bool)(this["ARCH_PREFETCHWT1"]));
            }
            set {
                this["ARCH_PREFETCHWT1"] = value;
            }
        }
    }
}
