//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntrinsicsDude {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkViolet")]
        public global::System.Drawing.Color SyntaxHighlighting_Intrinsic {
            get {
                return ((global::System.Drawing.Color)(this["SyntaxHighlighting_Intrinsic"]));
            }
            set {
                this["SyntaxHighlighting_Intrinsic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Teal")]
        public global::System.Drawing.Color SyntaxHighlighting_Register {
            get {
                return ((global::System.Drawing.Color)(this["SyntaxHighlighting_Register"]));
            }
            set {
                this["SyntaxHighlighting_Register"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkOrange")]
        public global::System.Drawing.Color SyntaxHighlighting_Misc {
            get {
                return ((global::System.Drawing.Color)(this["SyntaxHighlighting_Misc"]));
            }
            set {
                this["SyntaxHighlighting_Misc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SyntaxHighlighting_On {
            get {
                return ((bool)(this["SyntaxHighlighting_On"]));
            }
            set {
                this["SyntaxHighlighting_On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StatementCompletion_On {
            get {
                return ((bool)(this["StatementCompletion_On"]));
            }
            set {
                this["StatementCompletion_On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_MMX {
            get {
                return ((bool)(this["ARCH_MMX"]));
            }
            set {
                this["ARCH_MMX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_SSE {
            get {
                return ((bool)(this["ARCH_SSE"]));
            }
            set {
                this["ARCH_SSE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_SSE2 {
            get {
                return ((bool)(this["ARCH_SSE2"]));
            }
            set {
                this["ARCH_SSE2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_SSE3 {
            get {
                return ((bool)(this["ARCH_SSE3"]));
            }
            set {
                this["ARCH_SSE3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_SSSE3 {
            get {
                return ((bool)(this["ARCH_SSSE3"]));
            }
            set {
                this["ARCH_SSSE3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_SSE41 {
            get {
                return ((bool)(this["ARCH_SSE41"]));
            }
            set {
                this["ARCH_SSE41"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_SSE42 {
            get {
                return ((bool)(this["ARCH_SSE42"]));
            }
            set {
                this["ARCH_SSE42"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_AVX {
            get {
                return ((bool)(this["ARCH_AVX"]));
            }
            set {
                this["ARCH_AVX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_AVX2 {
            get {
                return ((bool)(this["ARCH_AVX2"]));
            }
            set {
                this["ARCH_AVX2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_AVX512_VL {
            get {
                return ((bool)(this["ARCH_AVX512_VL"]));
            }
            set {
                this["ARCH_AVX512_VL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_AVX512_DQ {
            get {
                return ((bool)(this["ARCH_AVX512_DQ"]));
            }
            set {
                this["ARCH_AVX512_DQ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_AVX512_BW {
            get {
                return ((bool)(this["ARCH_AVX512_BW"]));
            }
            set {
                this["ARCH_AVX512_BW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_AVX512_ER {
            get {
                return ((bool)(this["ARCH_AVX512_ER"]));
            }
            set {
                this["ARCH_AVX512_ER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_AVX512_F {
            get {
                return ((bool)(this["ARCH_AVX512_F"]));
            }
            set {
                this["ARCH_AVX512_F"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_AVX512_CD {
            get {
                return ((bool)(this["ARCH_AVX512_CD"]));
            }
            set {
                this["ARCH_AVX512_CD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_BMI1 {
            get {
                return ((bool)(this["ARCH_BMI1"]));
            }
            set {
                this["ARCH_BMI1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_BMI2 {
            get {
                return ((bool)(this["ARCH_BMI2"]));
            }
            set {
                this["ARCH_BMI2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_FMA {
            get {
                return ((bool)(this["ARCH_FMA"]));
            }
            set {
                this["ARCH_FMA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_MPX {
            get {
                return ((bool)(this["ARCH_MPX"]));
            }
            set {
                this["ARCH_MPX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SignatureHelp_On {
            get {
                return ((bool)(this["SignatureHelp_On"]));
            }
            set {
                this["SignatureHelp_On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_ADX {
            get {
                return ((bool)(this["ARCH_ADX"]));
            }
            set {
                this["ARCH_ADX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_FP16C {
            get {
                return ((bool)(this["ARCH_FP16C"]));
            }
            set {
                this["ARCH_FP16C"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_PCLMULQDQ {
            get {
                return ((bool)(this["ARCH_PCLMULQDQ"]));
            }
            set {
                this["ARCH_PCLMULQDQ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_CLFLUSHOPT {
            get {
                return ((bool)(this["ARCH_CLFLUSHOPT"]));
            }
            set {
                this["ARCH_CLFLUSHOPT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_FXSR {
            get {
                return ((bool)(this["ARCH_FXSR"]));
            }
            set {
                this["ARCH_FXSR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_KNCNI {
            get {
                return ((bool)(this["ARCH_KNCNI"]));
            }
            set {
                this["ARCH_KNCNI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_AES {
            get {
                return ((bool)(this["ARCH_AES"]));
            }
            set {
                this["ARCH_AES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_AVX512_PF {
            get {
                return ((bool)(this["ARCH_AVX512_PF"]));
            }
            set {
                this["ARCH_AVX512_PF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_AVX512_IFMA {
            get {
                return ((bool)(this["ARCH_AVX512_IFMA"]));
            }
            set {
                this["ARCH_AVX512_IFMA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_AVX512_VBMI {
            get {
                return ((bool)(this["ARCH_AVX512_VBMI"]));
            }
            set {
                this["ARCH_AVX512_VBMI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_LZCNT {
            get {
                return ((bool)(this["ARCH_LZCNT"]));
            }
            set {
                this["ARCH_LZCNT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_INVPCID {
            get {
                return ((bool)(this["ARCH_INVPCID"]));
            }
            set {
                this["ARCH_INVPCID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_MONITOR {
            get {
                return ((bool)(this["ARCH_MONITOR"]));
            }
            set {
                this["ARCH_MONITOR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_POPCNT {
            get {
                return ((bool)(this["ARCH_POPCNT"]));
            }
            set {
                this["ARCH_POPCNT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_RDRAND {
            get {
                return ((bool)(this["ARCH_RDRAND"]));
            }
            set {
                this["ARCH_RDRAND"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_RDSEED {
            get {
                return ((bool)(this["ARCH_RDSEED"]));
            }
            set {
                this["ARCH_RDSEED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_TSC {
            get {
                return ((bool)(this["ARCH_TSC"]));
            }
            set {
                this["ARCH_TSC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_RDTSCP {
            get {
                return ((bool)(this["ARCH_RDTSCP"]));
            }
            set {
                this["ARCH_RDTSCP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_FSGSBASE {
            get {
                return ((bool)(this["ARCH_FSGSBASE"]));
            }
            set {
                this["ARCH_FSGSBASE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_SHA {
            get {
                return ((bool)(this["ARCH_SHA"]));
            }
            set {
                this["ARCH_SHA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_RTM {
            get {
                return ((bool)(this["ARCH_RTM"]));
            }
            set {
                this["ARCH_RTM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_XSAVE {
            get {
                return ((bool)(this["ARCH_XSAVE"]));
            }
            set {
                this["ARCH_XSAVE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_XSAVEC {
            get {
                return ((bool)(this["ARCH_XSAVEC"]));
            }
            set {
                this["ARCH_XSAVEC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_XSS {
            get {
                return ((bool)(this["ARCH_XSS"]));
            }
            set {
                this["ARCH_XSS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_XSAVEOPT {
            get {
                return ((bool)(this["ARCH_XSAVEOPT"]));
            }
            set {
                this["ARCH_XSAVEOPT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_PREFETCHWT1 {
            get {
                return ((bool)(this["ARCH_PREFETCHWT1"]));
            }
            set {
                this["ARCH_PREFETCHWT1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HideStatementCompletionIncompatibleReturnType_On {
            get {
                return ((bool)(this["HideStatementCompletionIncompatibleReturnType_On"]));
            }
            set {
                this["HideStatementCompletionIncompatibleReturnType_On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DecorateIncompatibleStatementCompletions_On {
            get {
                return ((bool)(this["DecorateIncompatibleStatementCompletions_On"]));
            }
            set {
                this["DecorateIncompatibleStatementCompletions_On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ARCH_IA32 {
            get {
                return ((bool)(this["ARCH_IA32"]));
            }
            set {
                this["ARCH_IA32"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HideStatementCompletionMmxRegisters_On {
            get {
                return ((bool)(this["HideStatementCompletionMmxRegisters_On"]));
            }
            set {
                this["HideStatementCompletionMmxRegisters_On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_RDPID {
            get {
                return ((bool)(this["ARCH_RDPID"]));
            }
            set {
                this["ARCH_RDPID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_CLWB {
            get {
                return ((bool)(this["ARCH_CLWB"]));
            }
            set {
                this["ARCH_CLWB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_AVX512_VPOPCNTDQ {
            get {
                return ((bool)(this["ARCH_AVX512_VPOPCNTDQ"]));
            }
            set {
                this["ARCH_AVX512_VPOPCNTDQ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_AVX512_4VNNIW {
            get {
                return ((bool)(this["ARCH_AVX512_4VNNIW"]));
            }
            set {
                this["ARCH_AVX512_4VNNIW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_AVX512_4FMAPS {
            get {
                return ((bool)(this["ARCH_AVX512_4FMAPS"]));
            }
            set {
                this["ARCH_AVX512_4FMAPS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_AVX512_VBMI2 {
            get {
                return ((bool)(this["ARCH_AVX512_VBMI2"]));
            }
            set {
                this["ARCH_AVX512_VBMI2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_AVX512_VNNI {
            get {
                return ((bool)(this["ARCH_AVX512_VNNI"]));
            }
            set {
                this["ARCH_AVX512_VNNI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_AVX512_BITALG {
            get {
                return ((bool)(this["ARCH_AVX512_BITALG"]));
            }
            set {
                this["ARCH_AVX512_BITALG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_AVX512_GFNI {
            get {
                return ((bool)(this["ARCH_AVX512_GFNI"]));
            }
            set {
                this["ARCH_AVX512_GFNI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_AVX512_VAES {
            get {
                return ((bool)(this["ARCH_AVX512_VAES"]));
            }
            set {
                this["ARCH_AVX512_VAES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_AVX512_VPCLMULQDQ {
            get {
                return ((bool)(this["ARCH_AVX512_VPCLMULQDQ"]));
            }
            set {
                this["ARCH_AVX512_VPCLMULQDQ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_AVX512_BF16 {
            get {
                return ((bool)(this["ARCH_AVX512_BF16"]));
            }
            set {
                this["ARCH_AVX512_BF16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_AVX512_VP2INTERSECT {
            get {
                return ((bool)(this["ARCH_AVX512_VP2INTERSECT"]));
            }
            set {
                this["ARCH_AVX512_VP2INTERSECT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_SVML {
            get {
                return ((bool)(this["ARCH_SVML"]));
            }
            set {
                this["ARCH_SVML"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARCH_AVX512_ENQCMD {
            get {
                return ((bool)(this["ARCH_AVX512_ENQCMD"]));
            }
            set {
                this["ARCH_AVX512_ENQCMD"] = value;
            }
        }
    }
}
